### ISSUE TITLE
model/input_representation.py 下stanfordcorenlp模块未注释

### ISSUE THREAD

**Issue by xinghudamowang** [sunyilgdx/SIFRank_zh#25]
model/input_representation.py 下stanfordcorenlp模块未注释。导致运行失败
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from model.method import SIFRank, SIFRank_plus
  File "/apdcephfs/private_markowu/proj/SIFRank_zh-master/model/method.py", line 9, in <module>
    from model import input_representation
  File "/apdcephfs/private_markowu/proj/SIFRank_zh-master/model/input_representation.py", line 9, in <module>
    from stanfordcorenlp import StanfordCoreNLP
ModuleNotFoundError: No module named 'stanfordcorenlp'

**Comment by jesuswa** [comment]
我认为你这个错误不是这块
我安装完pip install overrides==3.1.0
装的是Successfully installed psutil-5.9.6 stanfordcorenlp-3.9.1.1
