### ISSUE TITLE
test.py文件执行报错

### ISSUE THREAD

**Issue by ghost** [sunyilgdx/SIFRank_zh#29]
Traceback (most recent call last):
  File "D:/Codes/Information-extraction/keyword-extraction/SIFRank_zh/test/test.py", line 16, in <module>
    ELMO = word_emb_elmo.WordEmbeddings(model_file)
  File "D:\Codes\Information-extraction\keyword-extraction\SIFRank_zh\embeddings\word_emb_elmo.py", line 19, in __init__
    self.elmo = Embedder(model_path)
  File "D:\Codes\Information-extraction\keyword-extraction\SIFRank_zh\elmoformanylangs\elmo.py", line 107, in __init__
    self.model, self.config = self.get_model()
  File "D:\Codes\Information-extraction\keyword-extraction\SIFRank_zh\elmoformanylangs\elmo.py", line 163, in get_model
    model.load_model(self.model_dir)
  File "D:\Codes\Information-extraction\keyword-extraction\SIFRank_zh\elmoformanylangs\frontend.py", line 206, in load_model
    map_location=lambda storage, loc: storage))
  File "D:\softwares\miniconda\envs\torch1.8\lib\site-packages\torch\nn\modules\module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ConvTokenEmbedder:
	size mismatch for word_emb_layer.embedding.weight: copying a param with shape torch.Size([140384, 100]) from checkpoint, the shape in current model is torch.Size([71222, 100]).
	size mismatch for char_emb_layer.embedding.weight: copying a param with shape torch.Size([15889, 50]) from checkpoint, the shape in current model is torch.Size([6169, 50]).

**Comment by hyacinth-prog** [comment]
你好，你的问题解决了吗，我也遇到了同样的问题

**Comment by HarmonRS** [comment]
这是因为token_embedder.pkl的原因 应该使用哈工大简体中文下载的zhs.model.tar_2.bz2压缩包下的token_embedder.pkl而不是179.zip包下的文件 替换后我成功执行了代码

**Comment by lwttttt** [comment]
> 这是因为token_embedder.pkl的原因 应该使用哈工大简体中文下载的zhs.model.tar_2.bz2压缩包下的token_embedder.pkl而不是179.zip包下的文件 替换后我成功执行了代码

能下载么我下不下来
